#
# softwinner 3G module driver.
#

obj-$(CONFIG_SW_3G_MODULE)	+= driver.o core.o
obj-$(CONFIG_HUAWEI_MU509)	+= mu509.o
obj-$(CONFIG_YUGA_CWM600)	+= cwm600.o
obj-$(CONFIG_OVIPHONE_EM55)	+= em55.o
obj-$(CONFIG_LONGCHEER_WM5608)	+= wm5608.o
