obj-y += axp-mfd.o

#axp 199
#Make this built-in, so that it will be loaded before I2C driver
obj-$(CONFIG_AW_AXP18) += axp18-board.o
obj-$(CONFIG_AW_AXP18) += axp18-regu.o
obj-$(CONFIG_AW_AXP18) += axp18-sply.o
obj-$(CONFIG_AW_AXP18) += virtual18.o
obj-$(CONFIG_AW_AXP18) += virtual18_dev.o

obj-$(CONFIG_AW_AXP19) += axp19-board.o
obj-$(CONFIG_AW_AXP19) += axp19-regu.o
obj-$(CONFIG_AW_AXP19) += axp19-sply.o
obj-$(CONFIG_AW_AXP19) += axp19-gpio.o
obj-$(CONFIG_AW_AXP19) += virtual19.o
obj-$(CONFIG_AW_AXP19) += virtual19_dev.o

obj-$(CONFIG_AW_AXP20) += axp20-board.o axp20-regu.o axp20-sply.o axp20-gpio.o virtual20.o virtual20_dev.o

obj-$(CONFIG_AW_AXP22) += axp22-board.o
obj-$(CONFIG_AW_AXP22) += axp22-regu.o
obj-$(CONFIG_AW_AXP22) += axp22-sply.o
obj-$(CONFIG_AW_AXP22) += axp22-gpio.o
obj-$(CONFIG_AW_AXP22) += virtual22.o
obj-$(CONFIG_AW_AXP22) += virtual22_dev.o
